#!/usr/bin/env bash
set -euo pipefail
CHANGED=$(git diff --cached --name-only -- 'content/creators/' 'templates/')
if [ -n "$CHANGED" ]; then
    echo "based.academy: Rebuilding site..."
    make -s all
    git add index.html feed.atom
fi
