["Smart Things"]
name = "Smart Things"
desc = "He is a 33 yr old boomer"
date = "Mar 31, 2026"

[Nijo]
name = "Nijo"
desc = "I am cool"
date = "Mar 31, 2026"

[Vimothee]
name = "Vimothee"
desc = "He looks like vimothee"
date = "Mar 31, 2026"

[Bugswriter]
name = "Bugswriter"
desc = "cool linux guy"
date = "Mar 31, 2026"
